steps:
- script: az login -u dembe.tshifaro@gmail.com -p dembeEdward123
  displayName: Azure Login
- script: az aks get-credentials -g mfa-aks -n mfa-cluster1
  displayName: Get credential
- script: kubectl get po
  displayName: List pods